# Generated by Django 3.1.5 on 2021-04-30 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('facebook_url', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=200, null=True)),
                ('twtter_url', models.CharField(blank=True, max_length=200, null=True)),
                ('linkdin_url', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='service')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=50)),
                ('detaiil', models.TextField()),
                ('espicial_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.construction')),
            ],
        ),
    ]
