# Generated by Django 3.1.5 on 2021-05-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_ourteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='linkdin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='twtter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
