# Generated by Django 3.1.5 on 2021-04-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=50)),
                ('adress', models.CharField(blank=True, max_length=100)),
                ('fax', models.CharField(blank=True, max_length=50)),
                ('smtpserver', models.CharField(blank=True, max_length=50)),
                ('smtpemail', models.CharField(blank=True, max_length=50)),
                ('smtppassword', models.CharField(blank=True, max_length=50)),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('youtube', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('twtter', models.CharField(blank=True, max_length=50)),
                ('aboutus', models.TextField(blank=True)),
                ('reference', models.TextField(blank=True)),
                ('contact', models.TextField(blank=True)),
                ('status', models.TextField(blank=True, choices=[('True', 'True'), ('False', 'False')])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('icon', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
