# Generated by Django 3.1.5 on 2021-04-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMesssage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('Note', models.CharField(blank=True, max_length=200)),
                ('ip', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('New', 'New'), ('Read', 'Read'), ('New', 'New')], default='New', max_length=40)),
                ('message', models.TextField(blank=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
